version: "3.3"
services:
    db:
        image: mongo
        ports:
          - 27017:27017
        environment:
          - MONGO_INITDB_DATABASE=sabidos
        networks:
          - sabidos
    api:
        build: .
        ports:
          - 8080:8080
        networks:
          - sabidos
        depends_on:
          - db  
networks:
  sabidos:
    driver: bridge

